name: Run Jest Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  nodejs:
    name: Example Action
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: yarn coverage
        run: yarn test --coverage
