name: Git Pull and Docker Update

on:
  push:
    branches:
      - main

jobs:
  replace-image:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH and Docker commands
        run: |
          ssh -o StrictHostKeyChecking=no root@45.63.66.64 << EOF
            cd /root/Result-Bot
            docker stop result-bot || true
            docker rm result-bot || true
            git stash
            git pull && echo "Git pull was successful" || echo "Git pull failed"
            docker build -t result-bot .
            docker run -d --name result-bot result-bot
          EOF
